#!/bin/bash

# Set default values
username="itspiyush"
password="root"
chrome_remote_desktop_url="https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb"

# Function to log messages
log() {
    echo "$(date +'%Y-%m-%d %H:%M:%S') - $1"
}

# Function to install packages
install_package() {
    package_url=$1
    log "Downloading $package_url"
    wget -q --show-progress "$package_url"
    log "Installing $(basename $package_url)"
    sudo dpkg --install $(basename $package_url)
    log "Fixing broken dependencies"
    sudo apt-get install --fix-broken -y
    rm $(basename $package_url)
}

# Installation steps
log "Starting installation"

# Create user
log "Creating user '$username'"
sudo useradd -m "$username"
echo "$username:$password" | sudo chpasswd
sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd

# Install Chrome Remote Desktop
install_package "$chrome_remote_desktop_url"

# Install XFCE desktop environment
log "Installing XFCE desktop environment"
sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes -y xfce4 desktop-base dbus-x11 xscreensaver

# Set up Chrome Remote Desktop session
log "Setting up Chrome Remote Desktop session"
sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'

# Disable lightdm service
log "Disabling lightdm service"
sudo systemctl disable lightdm.service

# VS Code installation
log "Installing VS Code"
sudo dpkg -i ./code.deb
sudo apt --fix-broken install -y

# Chrome installation
log "Installing Chrome"
sudo dpkg -i ./chrome.deb
sudo apt --fix-broken install -y

# MongoDB installation
log "Installing MongoDB"
sudo dpkg -i ./db.deb
sudo apt --fix-broken install -y

# Start Chrome Remote Desktop host with specified code and set PIN
log "Starting Chrome Remote Desktop host"
DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AVG7fiRbeXf0icXOjFbV503l4r6TG03eNurHnhpf0m3S28PyFf874UWSCtDn770YrWnIxQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)

# Set PIN for Chrome Remote Desktop
log "Setting PIN for Chrome Remote Desktop"
echo "123456" | sudo tee /etc/chrome-remote-desktop/pin

log "Installation completed successfully"

# Infinite loop script
while true; do
    echo "innocent_jimmy" # print "innocent_jimmy"
    sleep 1 # wait for 1 second
done # end the loop
